---
title: "earthquake_analysis"
author: "julianascii"
---

```{r message=FALSE, warning=FALSE}

# load packages
library(dplyr)
library(readr)
library(ggplot2)
```

```{r}
df <- read_csv("earthquake_data_tsunami.csv")
```


```{r}
# inspect the data frame
glimpse(df)
head(df) 
summary(df)
```

```{r}
# analyze relationships
# determine if deeper earthquakes are generally weaker
d_vs_m_viz <- ggplot(df, aes(x = depth, y = magnitude)) +
              geom_point(alpha = 0.5) +
              labs(title = "Depth vs Magnitude",
                   x = "Depth of the Earthquake",
                   y = "Magnitude of the Earthquake")
d_vs_m_viz
```

```{r}

df$tsunami <- ifelse(df$tsunami == 1, "Tsunami", "No Tsunami")

# analyze the occurence of strong earthquakes since 2020 (magnitude 6.0-6.9)
strong_eq_since_2020 <- df %>%
  group_by(magnitude, Year) %>%
  filter(magnitude > 5.9, 
         magnitude < 7.0, 
         Year > 2019) %>%
  summarize(count = n(), 
            tsunami_generating = n())
strong_eq_since_2020

# analyze the mean magnitude of earthquakes given a month + frequency
months_mag_2020_to_present <- df %>%
  filter(Year > 2019) %>%
  group_by(Month) %>%
  summarize(mean_magnitude = mean(magnitude),
            count = n())
months_mag_2020_to_present
```

```{r}
# analyze if earthquakes with tsunamis have shallower depths or greater magnitudes
tsunami_vs_no_tsunami <- df %>%
  group_by(tsunami) %>%
  summarize(avg_depth = mean(depth),
            avg_magnitude = mean(magnitude))
tsunami_vs_no_tsunami
```

```{r}
# check for unusually deep or high-magnitude events
anomaly <- df %>%
  filter(magnitude >= 7.5,
         depth >= 600)
anomaly
```

```{r}
# finding areas with more earthquake occurence
viz <- ggplot(df, aes(x = longitude, 
                      y = latitude)) +
       geom_point(aes(color = magnitude), 
                  alpha = 0.5) +
       labs(title = "Recorded Magnitudes of Earthquakes",
            subtitle = "Given a Longitude and Latitude",
            x = "Longitude",
            y = "Latitude",
            color = "Magnitude")
viz
```

```{r}
# determine earthquake frequency per year and month
table(df$Year, df$Month)

# earthquake counts by month
ggplot(df, aes(x = Month, y = mmi)) + geom_boxplot()

# average magnitude per month or year
ggplot(df, aes(x = Month, y = Year)) + 
       geom_point(aes(color = magnitude), 
                  alpha = 0.3) +
       labs(title = "Magnitudes per Month in a Year")

# mean, median, min, max for magnitude and depth
mean(df$magnitude)
median(df$magnitude)
min(df$magnitude)
max(df$magnitude)
mean(df$depth)
median(df$depth)
min(df$depth)
max(df$depth)
```